baseURL = "https://supamakoto.de/"
languageCode = "de"
title = "supamakoto"
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  description = "Kurze Beschreibung deines Blogs"
  footerText = 'Auf dieser Website werden keine Daten gesammelt. <a href="https://www.socialmediawatchblog.de/impressum/">Impressum</a>'
[menu]
  [[menu.main]]
    name = "Über"
    url  = "/ueber/"
    weight = 1

[taxonomies]
  tag = "tags"

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS"]