baseURL = "https://supamakoto.de/"
languageCode = "de"
title = "martinfehrensen"
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  description = "Kurze Beschreibung deines Blogs"
  footerText = 'Auf dieser Website werden keine Daten gesammelt.'
[menu]
  [[menu.main]]
    name = "Über"
    url  = "/ueber/"
    weight = 1
  [[menu.main]]
    name = "Newsletter"
    url  = "/newsletter/"
    weight = 2

[taxonomies]
  tag = "tags"

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS"]